# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImage_iOS' do
	platform :ios, '9.0'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for GPUImage_iOS
inherit! :search_paths
    pod 'TPCircularBuffer'
    pod 'NSObjectObjCExceptionExtension'

end

target 'GPUImage_macOS' do
	platform :osx, '10.13'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for GPUImage_macOS

    

end
